name: dockerhub-description

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/description.yml'
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  dockerhubdescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ctlinux/xen-orchestra
